org.gradle.jvmargs=-Xmx1G -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3067 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3067
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.133
neo_version_range=[21.1,)
loader_version_range=[1,)

mod_id=alarideable
mod_name=AsLongAsRideable
mod_license=AGPL-3.0-only
mod_version=1.0.0
mod_group_id=committee.nova.alarideable.neoforge
mod_authors=Tapio (original), Nova Committee
mod_description=Ride skeleton horses and zombie horses as long as they are rideable.
