modLoader = "lowcodefml"
loaderVersion = "[38,)"
license = "GNU AGPL 3.0"
[[mods]]
modId = "alarideable"
version = "${file.jarVersion}"
displayName = "AsLongAsRideable"
authors = "Tapio"
displayTest = "IGNORE_SERVER_VERSION"
description = "Make skeleton horse / zombie horse defaultly tameable & rideable"
